// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// ignore_for_file: argument_type_not_assignable
const List<String> routeNames = <String>[
  'openjmu://add-comment',
  'openjmu://add-forward',
  'openjmu://app-center-page',
  'openjmu://backpack',
  'openjmu://changelog-page',
  'openjmu://chat-app-message-page',
  'openjmu://edit-profile-page',
  'openjmu://font-scale',
  'openjmu://home',
  'openjmu://image-crop',
  'openjmu://image-viewer',
  'openjmu://in-app-webview',
  'openjmu://login',
  'openjmu://news-detail',
  'openjmu://notifications',
  'openjmu://post-detail',
  'openjmu://publish-post',
  'openjmu://publish-team-post',
  'openjmu://scan-qr-code',
  'openjmu://search',
  'openjmu://settings',
  'openjmu://splash',
  'openjmu://switch-startup',
  'openjmu://team-post-detail',
  'openjmu://user-list-page',
  'openjmu://user-page',
  'openjmu://user-qr-code',
];

class Routes {
  const Routes._();

  /// '新增评论'
  ///
  /// [name] : 'openjmu://add-comment'
  ///
  /// [routeName] : '新增评论'
  ///
  /// [arguments] : [post, comment]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const String openjmuAddComment = 'openjmu://add-comment';

  /// '新增转发'
  ///
  /// [name] : 'openjmu://add-forward'
  ///
  /// [routeName] : '新增转发'
  ///
  /// [arguments] : [post]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const String openjmuAddForward = 'openjmu://add-forward';

  /// '应用中心'
  ///
  /// [name] : 'openjmu://app-center-page'
  ///
  /// [routeName] : '应用中心'
  static const String openjmuAppCenterPage = 'openjmu://app-center-page';

  /// '背包页'
  ///
  /// [name] : 'openjmu://backpack'
  ///
  /// [routeName] : '背包页'
  static const String openjmuBackpack = 'openjmu://backpack';

  /// '版本履历'
  ///
  /// [name] : 'openjmu://changelog-page'
  ///
  /// [routeName] : '版本履历'
  static const String openjmuChangelogPage = 'openjmu://changelog-page';

  /// '应用消息页'
  ///
  /// [name] : 'openjmu://chat-app-message-page'
  ///
  /// [routeName] : '应用消息页'
  ///
  /// [arguments] : [app]
  static const String openjmuChatAppMessagePage =
      'openjmu://chat-app-message-page';

  /// '编辑资料页'
  ///
  /// [name] : 'openjmu://edit-profile-page'
  ///
  /// [routeName] : '编辑资料页'
  static const String openjmuEditProfilePage = 'openjmu://edit-profile-page';

  /// '更改字号页'
  ///
  /// [name] : 'openjmu://font-scale'
  ///
  /// [routeName] : '更改字号页'
  static const String openjmuFontScale = 'openjmu://font-scale';

  /// '首页'
  ///
  /// [name] : 'openjmu://home'
  ///
  /// [routeName] : '首页'
  ///
  /// [arguments] : [initAction]
  static const String openjmuHome = 'openjmu://home';

  /// '图片裁剪'
  ///
  /// [name] : 'openjmu://image-crop'
  ///
  /// [routeName] : '图片裁剪'
  static const String openjmuImageCrop = 'openjmu://image-crop';

  /// '图片浏览'
  ///
  /// [name] : 'openjmu://image-viewer'
  ///
  /// [routeName] : '图片浏览'
  ///
  /// [arguments] : [index, pics, needsClear, post, heroPrefix]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const String openjmuImageViewer = 'openjmu://image-viewer';

  /// '网页浏览'
  ///
  /// [name] : 'openjmu://in-app-webview'
  ///
  /// [routeName] : '网页浏览'
  ///
  /// [arguments] : [url, title, app, withCookie, withAppBar, withAction, withScaffold, keepAlive]
  static const String openjmuInAppWebview = 'openjmu://in-app-webview';

  /// '登录页'
  ///
  /// [name] : 'openjmu://login'
  ///
  /// [routeName] : '登录页'
  static const String openjmuLogin = 'openjmu://login';

  /// '新闻详情页'
  ///
  /// [name] : 'openjmu://news-detail'
  ///
  /// [routeName] : '新闻详情页'
  ///
  /// [arguments] : [news]
  static const String openjmuNewsDetail = 'openjmu://news-detail';

  /// '通知页'
  ///
  /// [name] : 'openjmu://notifications'
  ///
  /// [routeName] : '通知页'
  ///
  /// [arguments] : [initialPage]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const String openjmuNotifications = 'openjmu://notifications';

  /// '动态详情页'
  ///
  /// [name] : 'openjmu://post-detail'
  ///
  /// [routeName] : '动态详情页'
  ///
  /// [arguments] : [post, index, fromPage, parentContext]
  static const String openjmuPostDetail = 'openjmu://post-detail';

  /// '发布动态'
  ///
  /// [name] : 'openjmu://publish-post'
  ///
  /// [routeName] : '发布动态'
  static const String openjmuPublishPost = 'openjmu://publish-post';

  /// '发布小组动态'
  ///
  /// [name] : 'openjmu://publish-team-post'
  ///
  /// [routeName] : '发布小组动态'
  static const String openjmuPublishTeamPost = 'openjmu://publish-team-post';

  /// '扫描二维码'
  ///
  /// [name] : 'openjmu://scan-qr-code'
  ///
  /// [routeName] : '扫描二维码'
  static const String openjmuScanQrCode = 'openjmu://scan-qr-code';

  /// '搜索页'
  ///
  /// [name] : 'openjmu://search'
  ///
  /// [routeName] : '搜索页'
  ///
  /// [arguments] : [content]
  static const String openjmuSearch = 'openjmu://search';

  /// '设置页'
  ///
  /// [name] : 'openjmu://settings'
  ///
  /// [routeName] : '设置页'
  static const String openjmuSettings = 'openjmu://settings';

  /// '启动页'
  ///
  /// [name] : 'openjmu://splash'
  ///
  /// [routeName] : '启动页'
  ///
  /// [arguments] : [initAction]
  static const String openjmuSplash = 'openjmu://splash';

  /// '切换启动页'
  ///
  /// [name] : 'openjmu://switch-startup'
  ///
  /// [routeName] : '切换启动页'
  static const String openjmuSwitchStartup = 'openjmu://switch-startup';

  /// '小组动态详情页'
  ///
  /// [name] : 'openjmu://team-post-detail'
  ///
  /// [routeName] : '小组动态详情页'
  ///
  /// [arguments] : [provider, type, postId]
  static const String openjmuTeamPostDetail = 'openjmu://team-post-detail';

  /// '用户列表页'
  ///
  /// [name] : 'openjmu://user-list-page'
  ///
  /// [routeName] : '用户列表页'
  ///
  /// [arguments] : [user, type]
  ///
  /// [argumentTypes] : [UserInfo, int]
  static const String openjmuUserListPage = 'openjmu://user-list-page';

  /// '用户页'
  ///
  /// [name] : 'openjmu://user-page'
  ///
  /// [routeName] : '用户页'
  ///
  /// [arguments] : [uid]
  ///
  /// [argumentTypes] : [int]
  static const String openjmuUserPage = 'openjmu://user-page';

  /// '用户二维码页'
  ///
  /// [name] : 'openjmu://user-qr-code'
  ///
  /// [routeName] : '用户二维码页'
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const String openjmuUserQrCode = 'openjmu://user-qr-code';
}
