import 'package:flutter/material.dart' show Color, Colors;

class ThemeUtils {
    static Color defaultColor = Color(0xFFE5322D);

    static List<Color> supportColors = [
        Colors.red[900],
        defaultColor,
        Colors.red[500],
        Colors.red[300],
        Colors.pink[900],
        Colors.pink[700],
        Colors.pink[500],
        Colors.pink[400],
        Colors.purple[900],
        Colors.purple[700],
        Colors.purple[500],
        Colors.purple[400],
        Colors.deepPurple[900],
        Colors.deepPurple[700],
        Colors.deepPurple[500],
        Colors.deepPurple[400],
        Colors.indigo[900],
        Colors.indigo[700],
        Colors.indigo[500],
        Colors.indigo[400],
        Colors.blue[900],
        Colors.blue[700],
        Colors.blue[500],
        Colors.blue[400],
        Colors.lightBlue[900],
        Colors.lightBlue[700],
        Colors.lightBlue[500],
        Colors.lightBlue[400],
        Colors.cyan[900],
        Colors.cyan[700],
        Colors.cyan[500],
        Colors.cyan[400],
        Colors.teal[900],
        Colors.teal[700],
        Colors.teal[500],
        Colors.teal[400],
        Colors.green[900],
        Colors.green[700],
        Colors.green[500],
        Colors.green[400],
        Colors.lightGreen[900],
        Colors.lightGreen[700],
        Colors.lightGreen[500],
        Colors.lightGreen[400],
        Colors.lime[900],
        Colors.lime[700],
        Colors.lime[500],
        Colors.lime[400],
        Colors.yellow[900],
        Colors.yellow[700],
        Colors.yellow[500],
        Colors.yellow[400],
        Colors.orange[900],
        Colors.orange[700],
        Colors.orange[500],
        Colors.orange[400],
        Colors.deepOrange[900],
        Colors.deepOrange[700],
        Colors.deepOrange[500],
        Colors.deepOrange[400],
        Colors.grey[900],
        Colors.grey[800],
        Colors.grey[700],
        Colors.grey[600],
        Colors.grey[400],
        Colors.grey[300],
        Colors.grey[200],
        Colors.grey[50],
    ];

    static Color currentColorTheme = defaultColor;

}
